version: '3'
services:
  api-db:
    image: postgres:15
    restart: "${CROSSWORD_DB_RESTART_POLICY:-unless-stopped}"
    ports:
      - "${CROSSWORD_DB_PORT:-5432}:5432"
    volumes:
      - "${CROSSWORD_DB_HOST_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data"
    environment:
      POSTGRES_NAME: "${CROSSWORD_DB_NAME:-crossword_dev}"
      POSTGRES_USER: "${CROSSWORD_DB_USER:-crossword_dev}"
      POSTGRES_PASSWORD: "${CROSSWORD_DB_PASSWORD:-crossword_dev}"
